- .gitignore
This folders mustn't be added on the .gitignore of the project, they're relative to the user environnement. Best practices advise to add the configuration of the user environnement in its own `.gitignore_global`.
> [UPT] Gitignore

- Resources/views/Form/formatter.html.twig
When switching from ckeditor, a JS error is thrown as  `{{ source_id }}_rich_instance` is not destroyed, only unbound.
This fix checks the status of `{{ source_id }}_rich_instance` to check the instance has been destroyed
> Fixed JS error when switching formatter from ckeditor

- Twig/Extension/TextFormatterExtension.php
Changes for compatibility with Twig 2.
There's only a danger here if someone has subclassed this extension class instead of using it directly.
> remove deprecated initRuntime method from twig extension, and remove unused instance variable for environment

- CHANGELOG.md
- Resources/config/twig.xml
- Resources/views/Form/formatter.html.twig
- Twig/Extension/CKEditorExtension.php
- UPGRADE-2.4.md
- composer.json
Upgrade `egeloen/ckeditor-bundle` to new major ~3.0
It's BC break, cause the `ckeditor_replace` tag has been renamed, so projects where the template `formatter.html.twig` has been overridden must be updated.
IMO sadly this commit can't be add to 2.3.x
> [UPT] CKEditor dependency to ~3.0

- Form/Type/FormatterType.php
- Resources/doc/reference/formatter_widget.rst
- Tests/Form/Type/FormatterTypeTest.php
```markdown
- Fix overwriting formatter selection
```
Symfony provides the possibility to give a default value for a choice type form field when setting up a form. The formatter type is such choice field.
It is currently however overwritten with the default formatter of the formatter pool without warning.
A common use case is to persist the format together with other settings of e.g. Sonata blocks and to re-edit them later in the same format, but currently the form field will just jump back to 'text' format and render the block content unusable.
Instead, the given value should only be overwritten if no valid format was given by the user.
> Fix overwriting formatter selection

- Tests/Block/FormatterBlockServiceTest.php
- composer.json
I am targetting this branch, because this is a fix for the unit tests in the stable branch.
```markdown
- unit tests use the correct namespace in imports.
```
This fixes the imports in the test cases. The sub namespace `Tests` isn't public anymore.
> Fixed wrong imports in tests

- Form/Type/FormatterType.php
- Form/Type/SimpleFormatterType.php
- Resources/config/form.xml
- Resources/views/Form/formatter.html.twig
- Tests/Form/Type/FormatterTypeTest.php
I am targetting this branch, because it fixes a bug that prevents loading CKEditor plugins from different sources.
Closes #196 
Fixes #196 
```markdown
- Added support for `PluginManagerInterface` in `FormatterType` and `SimpleFormatterType`
```
Fixes CKEditor plugins loading in the RichHTML widget.
> CKEditor custom plugins loading fix (#196)

- Form/Type/FormatterType.php
I am targetting this branch, because is a BC fix.
Rebase of #146
```markdown
- Fixed `FormatterType` for symfony >=3.0
```
`FormatterType` can't be used in symfony 3.*
> Improved symfony 3 support

- Form/Type/FormatterType.php
I am targetting this branch, because this is a patch.
```markdown
- Fixed duplicate translation on the format selector
```
The options in a choice list were translated two times, once in the php classes and a second time in the twig template.
> Fixed duplicate translation

- Admin/CkeditorAdminExtension.php
- composer.json
I am targetting this branch, because this is a BC patch.
```markdown
- Removed deprecation warning for `AdminExtension` usage.
```
Uses the new `AbstractAdminExtension` class.
> Remove deprecation warning for Admin class

- Resources/views/Form/ckeditor.html.twig
- Resources/views/Form/formatter.html.twig
Fixes https://github.com/sonata-project/SonataFormatterBundle/issues/125
```markdown
- Field with `sonata_simple_formatter_type` widget in a block in sonata page's composer doesn't update
```
When inserting a `sonata_simple_formatter_type` field in a custom block in sonata page, the content never gets updated when saving.
> fix simple widget not updating in sonata page block #125

- Form/Type/FormatterType.php
I am targetting this branch, because this is a patch.
Fixes #210
```markdown
- Fixed usage of `choice_translation_domain` in `FormatterType`
```
Checks symfony version when using this option.
> Check symfony version when using choice_translation_domain

- DependencyInjection/Configuration.php
- DependencyInjection/SonataFormatterExtension.php
- Formatter/Pool.php
- Resources/config/formatter.xml
- Tests/Form/EventListener/FormatterListenerTest.php
- Tests/Form/Type/FormatterTypeTest.php
- Tests/Formatter/PoolTest.php
- Tests/Validator/Constraints/FormatterValidatorTest.php
- UPGRADE-3.x.md
I am targetting this branch, because this is BC (addind a deprecation notice).
```markdown
- not specifying the `default_formatter` configuration node is deprecated
- specifying a logger through the `SonataFormatterBundle\Formatter\Pool` constructor is deprecated in favor of specifying it through `setLogger` method
- not specifying a default formatter to the `SonataFormatterBundle\Formatter\Pool` constructor
```
See #221
> Add missing deprecations

- DependencyInjection/Configuration.php
- DependencyInjection/SonataFormatterExtension.php
- Form/Type/FormatterType.php
- Form/Type/SimpleFormatterType.php
- Formatter/Pool.php
- Tests/Form/Type/FormatterTypeTest.php
- Tests/Formatter/PoolTest.php
- Tests/Validator/Constraints/FormatterValidatorTest.php
- composer.json
I am targetting this branch, because bumping minor version of some deps is considered major.
```markdown
- support for PHP 5.3 through 5.5 was dropped
- support for Symfony 2.3 through 2.7 was dropped
```
This prepares the next major release
> Drop old versions

- Form/Type/FormatterType.php
- Form/Type/SimpleFormatterType.php
- Resources/config/form.xml
- Resources/views/Form/ckeditor.html.twig
- Tests/Form/Type/FormatterTypeTest.php
I am targetting this branch, because it's a patch that add possibility without any BC break.
No issue about CKeditor's template.
```markdown
- Added the possibility to use `templates` defined in your `ivory_ckeditor.yml` in the `sonata_formatter_type` and `sonata_simple_formatter_type`
```
If you are using `templates` from CKeditor / IvoryCKeditorBundle, they are now automatically included in the template by `sonata_formatter_type` and `sonata_simple_formatter_type`.
> Add ckeditor templates in sonata_formatter_type and sonata_simple_formatter_type

- Resources/views/Form/formatter.html.twig
I am targetting 3.x, because it's just a small BC template fix.
```markdown
- Broken markitup header for rawhtml format in sonata_simple_formatter_type_widget
```
When using rawhtml format markitup needs a "html" class to be added to the parent in order to show the header icons. This was already set up for sonata_formatter_type_widget, but not for sonata_simple_formatter_type_widget, so I fixed that. It's ugly but it works.
> Fixed rawhtml format in sonata_simple_formatter_type_widget

- Extension/BaseExtension.php
- Extension/BaseProxyExtension.php
- Tests/Formatter/PoolTest.php
- Tests/Formatter/TwigFormatterTest.php
- composer.json
I am targetting this branch, because this is BC.
Fixes https://github.com/sonata-project/SonataMediaBundle/pull/1184
```markdown
- support for Twig 2.0
```
Adds support for the latest major release.
> Allow twig 2.0

- Tests/Form/EventListener/FormatterListenerTest.php
- Tests/Form/Type/FormatterTypeTest.php
- Tests/Formatter/MarkdownFormatterTest.php
- Tests/Formatter/PoolTest.php
- Tests/TestCase.php
- Tests/Validator/Constraints/FormatterValidatorTest.php
I am targetting this branch, because this is for tests only.
The method `getMock` is deprecated.
> Removed deprecated getMock in unit tests

- Block/FormatterBlockService.php
- Tests/Block/FormatterBlockServiceTest.php
- Tests/Formatter/PoolTest.php
- composer.json
I am targetting this branch, because this is BC.
Removed some deprecations throwed by tests. There are two remaining but not part of this bundle. They are part from block bundle, and they are already fixed (not on a release tho).
> Removed deprecations

- Twig/Extension/TextFormatterExtension.php
I am targetting this branch, because this is a bug fix.
```markdown
- Remove wrong implements from TextFormatterExtension
```
TextFormatterExtension was implementing an interface `Twig_Extension_InitRuntimeInterface` that is not implementing because it is missing the method.
This method was removed pre 3.0 so this is a bugfix. This is the commit: https://github.com/sonata-project/SonataFormatterBundle/commit/50fdf29b67b386be0fe06b6804bf00097e21fbb3
> Removed TextFormatterExtension implements

- Block/FormatterBlockService.php
I am targetting this branch, because it is bugfix reported in PR #234.
- Fixed issue with saving `sonata.formatter.block.formatter` when using within SonataAdminBundle (or Sonata sandbox project)
Typo error has been spotted in merged PR #234, this is just fix for that typo error.
> [BUGFIX] Fixing typo in PR #234

- DependencyInjection/SonataFormatterExtension.php
- Resources/doc/reference/installation.rst
- Tests/DependencyInjection/SonataFormatterExtensionTest.php
- Tests/Twig/Loader/LoaderSelectorTest.php
- Twig/Loader/LoaderSelector.php
- composer.json
I am targeting this branch, because this should be BC.
Refs #237 
```markdown
- Twig 2.0 compatibility
```
The goal of this PR is to fix Twig 2.0 compatibility
> Fixes/twig 2.0

- composer.json
I am targeting this branch, because this is BC and allows travis to pass.
Closes https://github.com/sonata-project/SonataMediaBundle/pull/1225
```markdown
- Added compatibility with 4.0 of admin bundle and media bundle
```
We are blocking installs of dev-master of media-bundle and admin-bundle, this makes builds to fail when using those versions. This change is inspired on: https://github.com/sonata-project/SonataMediaBundle/blob/3.x/composer.json#L73.
But actually on that same composer.json there is another dependency blocking 4.0.
How do we handle this? @sonata-project/contributors
> Added compatibility with 4.0 of admin bundle and media bundle

- Tests/Form/Type/SimpleFormatterTypeTest.php
- composer.json
- phpunit.xml.dist
```markdown
- Add compatibility with `egeloen/ckeditor-bundle 5.0`
```
IvoryCkEditorBundle 5.0.0 was released some days ago, this PR enables to install it with SonataFormatterBundle
> Add compatibility with egeloen/ckeditor-bundle 5.0

- Controller/CkeditorAdminController.php
- Tests/Controller/CkeditorAdminControllerTest.php
- composer.json
```markdown
- Use `request_stack`if it is present on `CkEditorAdminController`
- Improve the way we set custom `formTheme` for twig
- Port minor fixes already applied on `SonataMediaBundle` media list
```
Improve compatibility with SF3, make code similar to MediaBundle.
> Refactor on browserAction

- Resources/views/Ckeditor/browser.html.twig
I am targeting this branch because it's a backward compatible (critical) fix.
```markdown
- Fix the files browser view
```
The usage of "sameas" feature of twig always was "same as". **This is a critical issue.**
The `sameas` token generates an error, at least in twig 2. As the following links specify, the current usage is wrong for any version of twig:
- https://twig.sensiolabs.org/doc/1.x/tests/sameas.html
- https://twig.sensiolabs.org/doc/2.x/tests/sameas.html
> Fix sameas usage in media browser file

- Formatter/Pool.php
- Tests/Formatter/PoolTest.php
I am targeting this branch, because this is a bugfix.
Closes #248
```markdown
- Fixed twig 2 bug when updating rich text
```
This fix will finally support twig 2.
> Fixed twig 2 bug when updating rich text

- Formatter/Pool.php
I am targeting this branch, because this is a bugfix.
Follow up of #252
```markdown
- Fixed passing null to transformer
```
When using the formatter and allow null values, twig 2 couldn't handle null values and will exit with an exception:
```
Template "__string_template__XXX" is not defined.
```
> Fixed passing null to transformer

- Resources/views/Ckeditor/browser.html.twig
I am targeting this branch, because it's a bug fix.
```markdown
- Fix the deprecated use of _self in twig template
```
In twig 2.x, `_self` returns the template name and need to be fix in this view.
> Fix twig 2.x deprecated use of _self

- docs/reference/ckeditor_medias.rst
- docs/reference/formatter_widget.rst
- docs/reference/usage.rst
- src/Block/FormatterBlockService.php
- src/Form/Type/FormatterType.php
- src/Form/Type/SimpleFormatterType.php
- tests/Form/Type/FormatterTypeTest.php
```markdown
- Removed BC layer for older symfony versions
```
> Removed symfony BC layer for old symfony versions

- src/Controller/CkeditorAdminController.php
- tests/Controller/CkeditorAdminControllerTest.php
```markdown
- Fix for getRuntime on Symfony older than 3.4
```
TwigRenderer is used as runtime until SF 3.4.
This code makes sure we retrieve the correct runtime for SF < 3.4
> Use FormRenderer runtime to maintain compatibility with Symfony 3.4

- src/Admin/CkeditorAdminExtension.php
- src/Block/FormatterBlockService.php
- src/Controller/CkeditorAdminController.php
- src/DependencyInjection/Configuration.php
- src/DependencyInjection/SonataFormatterExtension.php
- src/Extension/BaseExtension.php
- src/Extension/BaseProxyExtension.php
- src/Extension/ControlFlowExtension.php
- src/Extension/ExtensionInterface.php
- src/Extension/GistExtension.php
- src/Form/EventListener/FormatterListener.php
- src/Form/Type/FormatterType.php
- src/Form/Type/SimpleFormatterType.php
- src/Formatter/BaseFormatter.php
- src/Formatter/FormatterInterface.php
- src/Formatter/MarkdownFormatter.php
- src/Formatter/Pool.php
- src/Formatter/RawFormatter.php
- src/Formatter/TextFormatter.php
- src/Formatter/TwigFormatter.php
- src/SonataFormatterBundle.php
- src/Twig/Extension/TextFormatterExtension.php
- src/Twig/Loader/LoaderSelector.php
- src/Twig/Node/GistNode.php
- src/Twig/SecurityPolicyContainerAware.php
- src/Twig/TokenParser/GistTokenParser.php
- src/Validator/Constraints/Formatter.php
- src/Validator/Constraints/FormatterValidator.php
I am targeting this branch, because this is pedantic.
This removes a lot of comments that are just tautological. Also, this migrates more classes to Twig namespaces. I ran my script only on `src/Twig` the other day 😅
> Remove tautologies

- docs/reference/formatter_widget.rst
- src/Form/Type/FormatterType.php
- tests/Form/Type/FormatterTypeTest.php
I am targeting this branch, because this is a bugfix.
Closes #236
```markdown
- Fixed form initialisation in sf3+
```
This should fix the init problem in symfony >=3.
> Fixed initialisation in sf3+

- src/Form/Type/SimpleFormatterType.php
- src/Resources/config/form.xml
- src/Resources/views/Form/ckeditor.html.twig
- tests/Form/Type/SimpleFormatterTypeTest.php
I am targeting this branch, because it's a simple feature that does not break BC.
```markdown
- Added support for stylesSet (ivory_ck_editor configuration)
```
Enables the use of custom styles in [ivory_ck_editor](https://github.com/egeloen/IvoryCKEditorBundle/blob/master/Resources/doc/usage/style.rst) when using SimpleFormatterType with the format 'richhtml'.
> Enable use of custom style sets from ivory_ck_editor

- composer.json
I consider this fixes this other PR https://github.com/sonata-project/dev-kit/pull/385 (because that was related to this bundle)
This changes nothing on what gets installed when using this bundle. But declaring explicit dependencies makes you use the versions correctly even when doing prefer-lowest. That makes the build faster, and improves the consistency on this bundle, because we know what is needed for this bundle to work exactly.
Labelled as pedantic cause it will change nothing for normal users
> Declare dependencies explicitly

- composer.json
I am targeting this branch, because this is a BC fix.
Closes #269
```markdown
- Added egeloen/ckeditor-bundle 6.0 dependency to composer.json
```
In order to satisfy Symfony 3.4 project dependencies using the SonataFormatterBundle, we require the newest version (6.0) of the egeloen/ckeditor-bundle bundle.
> Allowing egeloen/ckeditor-bundle 6.0

- composer.json
- src/Controller/CkeditorAdminController.php
```markdown
- deprecations from the admin bundle about `render` vs `renderWithExtraParams`
```
render() has been planned for removal and should no longer be used.
> Use renderWithExtraParams() instead of render()

- src/Form/Type/FormatterType.php
- src/Form/Type/SimpleFormatterType.php
- src/Resources/config/form_fos.xml
- src/Resources/config/form_ivory.xml
- tests/Form/Type/FormatterTypeTest.php
I am targeting this branch, because this is a bug fix and BC.
```markdown
- Ckeditor toolbar config not loading
```
v5 of https://github.com/egeloen/IvoryCKEditorBundle introduced a [toolbar manager](https://github.com/egeloen/IvoryCKEditorBundle/commit/7ef1c96f6958b458545f336a10178f033764fd5f) to load the toolbar configuration.
This was never implemented in this bundle although it is compatible with V5 and V6 of the IvoryCKEditorBundle.
> Fix ckeditor toolbar config

- src/Twig/SecurityPolicyContainerAware.php
- tests/Formatter/TwigFormatterTest.php
- tests/Twig/SecurityPolicyContainerAwareTest.php
In 155337dbece5cbaefac716da7e3b3b93096f7007, I made the wrong assumption
that Twig would have type hints, and introduced a BC break a class that
implements a Twig interface. This removes those type hints, and adds a
test to be sure those cannot be added again by mistake.
I am targeting this branch, because this fix is only relevant on master.
Refs #336 
None, since nothing is released yet.
> Remove some typehints

- docs/reference/ckeditor_medias.rst
- tests/Formatter/TwigFormatterTest.php
I am targeting this branch, because it is docs update.
Since CKEditor 4.9.0 `xhr` is default upload method. SonataMediaBundle require `form` method. Without this option CKEditor 4.9.0+ after upload show alert "Incorrect server response" error. Because in `xhr` mode it expects json response:
```
{
"uploaded": 1,
"fileName": "foo.jpg",
"url": "/files/foo.jpg"
}
```
while SonataMediaBundle respond in `form` mode:
```
<script>window.parent.CKEDITOR.tools.callFunction(1, "/uploads/media/default/0001/15/3754353373720696f993c48ed28dac1287a51c86.jpeg");</script>
```
see: https://ckeditor.com/cke4/release/CKEditor-4.9.0
"1365: The File Browser plugin uses XHR requests by default."
> update CKEditor upload to SonataMediaBundle docs

- composer.json
We use it, we should require it, instead of assuming it is installed.
> Require psr/log 1.0

- src/Form/EventListener/FormatterListener.php
- src/Form/Type/FormatterType.php
- src/Formatter/Pool.php
- src/Formatter/PoolInterface.php
- src/Twig/Extension/TextFormatterExtension.php
- src/Validator/Constraints/FormatterValidator.php
I am targeting this branch, because this is BC (only constructor signatures are affected).
```markdown
- the `final` Sonata\FormatterBundle\Formatter\Pool class now implements a `Sonata\FormatterBundle\Formatter\PoolInterface`
```
Introduce an interface for a final class
> Introduce PoolInterface

- tests/Form/Type/SimpleFormatterTypeTest.php
This is intentional, we want to see if the form fails to build.
I am targeting this branch, because this is pedantic. There is another warning left, but it comes from a parent test in the core bundle.
> Mark tests without assertions as such

- src/Form/EventListener/FormatterListener.php
I am targeting this branch, because this is a patch.
```markdown
- Catch null values in FormatterListener
```
The `FormatterListener` was failing if you tried to transform a null value.
> Added null check to FormatterListener

- src/Controller/CkeditorAdminController.php
I am targeting this branch, because the error appears in 4.1.1
Closes #370
```markdown
- Wrong typehint on `setFormTheme` method
```
> Minor - fix type hint

- src/DependencyInjection/SonataFormatterExtension.php
- tests/Form/EventListener/FormatterListenerTest.php
- tests/Form/Type/FormatterTypeTest.php
- tests/Form/Type/SimpleFormatterTypeTest.php
- tests/Formatter/MarkdownFormatterTest.php
- tests/Formatter/PoolTest.php
I removed a few Twig deprecations in the `SonataFormatterExtension` class.
I am targeting this branch, because it is backward compatible.
Closes #407
```markdown
- Removed Twig deprecations
```
A lot of other deprecations remain but they are from the CKEditor bundle.
> Removed Twig deprecations

- src/Form/Type/SimpleFormatterType.php
- tests/Form/Type/SimpleFormatterTypeTest.php
Fix ignoring fos_ck_editor.configs.toolbar param in application config when using SimpleFormatterType.
I am targeting this branch, because setting up toolbar type in main config is important for easy using SimpleFormatterType.
Set up toolbar as full, standard or basic was overriden by $options['ckeditor_toolbar_icons']
```markdown
- Fix posibility to easily switch the toolbar configuration by using the full, standard or basic keyword as toolbar with SimpleFormatterType
```
> Fix ignoring fos_ck_editor.configs.toolbar param in config.yml

- src/DependencyInjection/SonataFormatterExtension.php
- src/Formatter/ExtendableFormatter.php
- src/Formatter/Formatter.php
- src/Formatter/FormatterInterface.php
- tests/Form/EventListener/FormatterListenerTest.php
- tests/Formatter/MarkdownFormatterTest.php
- tests/Formatter/RawFormatterTest.php
- tests/Formatter/TextFormatterTest.php
- tests/Formatter/TwigFormatterTest.php
- tests/Validator/Constraints/FormatterValidatorTest.php
Some formatters do not support extensions (e.g. https://github.com/sonata-project/SonataFormatterBundle/blob/4.x/src/Formatter/TwigFormatter.php#L56), so we should split the existing interface
```markdown
- Added new `Formatter` interface
- Added new `ExtendableFormatter` interface
```
> Add new interface for extendable formatters

- composer.json
This change will allow install optionally only CoreBundle v3.20 (which constains all deprecations notes).
- update CoreBundle to 3.20
- remove deprecations
- remove CoreBundle
- upgrade extensions to 1.x
I am targeting this branch, because this change respect BC.
```markdown
Support for Symfony < 4.3
```
> Drop support for symfony <4.3

- composer.json
Allow some symfony/* dependencies to use version ^5.1, since these major versions don't have breaking changes. See:
* https://github.com/symfony/options-resolver/blob/v5.0.0/CHANGELOG.md#500;
* https://github.com/symfony/property-access/blob/v5.0.0/CHANGELOG.md.
I am targeting this branch, because these changes respect BC.
Depends on sonata-project/SonataAdminBundle#6299, sonata-project/SonataMediaBundle#1786.
```markdown
- Added support for symfony/options-resolver:^5.1;
- Added support for symfony/property-access:^5.1.
```
> Allow some symfony/* dependencies to use version ^5.1

- composer.json
- tests/Validator/Constraints/FormatterValidatorTest.php
This update seems to have no side effects.
I also found an outdated docblock in FormatterValidatorTest.php.
I am targeting this branch, because it is backwards compatible.
```markdown
- Added support for `symfony/validator` ^5.1.
```
> Add support for symfony/validator ^5.1

- .github/workflows/test.yaml
- composer.json
I am targeting this branch, because this is bc.
Dev-kit pr: https://github.com/sonata-project/dev-kit/pull/1492
```markdown
- Added php 8 support
```
> Add php 8 Support
