- Resources/doc/reference/formatter_widget.rst
Hi,
Fixed a little typo in the formatter_widget.rst documentation.
> fix typo in formatter_widget.rst

- Twig/Extension/TextFormatterExtension.php
Fixes #119 
Thanks @wodka for reporting.
> Fix twig simple filter signature

- Resources/doc/reference/formatter_widget.rst
> quote meta characters

- DependencyInjection/Compiler/CKEditorCompilerPass.php
- SonataFormatterBundle.php
- Twig/Extension/CKEditorExtension.php
- composer.json
No BC in this bundle during the migration 3.x to 4.x
> [ADD] Support for egeloen/ckeditor-bundle 4.x

- SonataFormatterBundle.php
I waited for several weeks to remove support myself 😢 😄
It missing a little piece of code
> Remove useless compiler pass since drop support ckeditor bundle 2 and 3

- composer.json
```markdown
- Added `SonataAdminBundle` to suggest 
- Added `SonataMediaBundle` to suggest 
```
The ``SonataAdminBundle`` and ``SonataMediaBundle`` should be suggested, because there is an integration in the admin backend.
> Added missing dependencies

- Controller/CkeditorAdminController.php
- Formatter/Pool.php
- Twig/Loader/LoaderSelector.php
- Twig/Node/GistNode.php
```markdown
- Missing / wrong phpdoc
```
Some phpdoc is missing or wrong.
> Fixed phpdoc

- Tests/Block/FormatterBlockServiceTest.php
```markdown
- Added tests for `FormatterBlockService`
```
Added tests for `FormatterBlockService`
> Adding missing tests for FormatterBlockService

- composer.json
```markdown
- Added `sllh/php-cs-fixer-styleci-bridge` dependency
```
The dependency is used for running php-cs-fixer.
> Added missing styleci-bridge

- composer.json
```markdown
- Added `sonata-project/admin-bundle` dependency for development
- Added `sonata-project/media-bundle` dependency for development
```
Added all used dependencies for developers. This will help while development, e.g. running code inspection.
> Added media and admin dependency for development

- Resources/doc/reference/formatter_widget.rst
Update the docs to document how to set ckeditor_context on a sonata_simple_formatter_type form field.
> update docs simple formatter widget

- Resources/translations/SonataFormatterBundle.it.xliff
> Add italian translation

- Block/FormatterBlockService.php
- DependencyInjection/SonataFormatterExtension.php
- Form/Type/FormatterType.php
- Form/Type/SimpleFormatterType.php
- Formatter/TwigFormatter.php
- Tests/Form/Type/FormatterTypeTest.php
- Twig/SecurityPolicyContainerAware.php
I am targetting this branch, because is BC.
> Some small fixes

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- .styleci.yml
- .travis.yml
- .travis/before_install_test.sh
- .travis/before_script_test.sh
- .travis/install_test.sh
- CHANGELOG.md
- CONTRIBUTING.md
- Controller/CkeditorAdminController.php
- DependencyInjection/SonataFormatterExtension.php
- Formatter/Pool.php
- README.md
- Resources/doc/index.rst
- Resources/doc/reference/installation.rst
- Resources/public/vendor/ckeditor/samples/assets/posteddata.php
- Resources/views/Ckeditor/browser.html.twig
- Tests/Controller/CkeditorAdminControllerTest.php
- Tests/DependencyInjection/SonataFormatterExtensionTest.php
- Tests/Form/Type/SimpleFormatterTypeTest.php
- Tests/Formatter/PoolTest.php
- Tests/Twig/Loader/LoaderSelectorTest.php
- Twig/Loader/LoaderSelector.php
- composer.json
- phpunit.xml.dist
> Merge stable

- src/Resources/translations/SonataFormatterBundle.ru.xliff
```markdown
- Added Russian translations
```
Added Russian translations.
> Added Russian translations

- docs/reference/ckeditor_medias.rst
- docs/reference/formatter_widget.rst
- docs/reference/usage.rst
- src/Block/FormatterBlockService.php
- src/Form/Type/FormatterType.php
- src/Form/Type/SimpleFormatterType.php
- src/Resources/translations/SonataFormatterBundle.ru.xliff
- tests/Controller/CkeditorAdminControllerTest.php
- tests/Form/Type/FormatterTypeTest.php
> Manual merge

- docs/reference/formatter_widget.rst
> use new sonata admin config nodes instead of overwriting template

- docs/reference/formatter_widget.rst
- docs/reference/installation.rst
> simplified installation instructions

- UPGRADE-4.0.md
- composer.json
- src/Block/FormatterBlockService.php
- src/Controller/CkeditorAdminController.php
- src/DependencyInjection/Configuration.php
- src/DependencyInjection/SonataFormatterExtension.php
- src/Extension/BaseExtension.php
- src/Extension/BaseProxyExtension.php
- src/Extension/ControlFlowExtension.php
- src/Extension/ExtensionInterface.php
- src/Extension/GistExtension.php
- src/Form/EventListener/FormatterListener.php
- src/Form/Type/FormatterType.php
- src/Form/Type/SimpleFormatterType.php
- src/Formatter/BaseFormatter.php
- src/Formatter/FormatterInterface.php
- src/Formatter/MarkdownFormatter.php
- src/Formatter/Pool.php
- src/Formatter/RawFormatter.php
- src/Formatter/TextFormatter.php
- src/Formatter/TwigFormatter.php
- src/Twig/Extension/TextFormatterExtension.php
- src/Twig/Loader/LoaderSelector.php
- src/Twig/Node/GistNode.php
- src/Twig/SecurityPolicyContainerAware.php
- src/Twig/TokenParser/GistTokenParser.php
- src/Validator/Constraints/Formatter.php
I am targeting this branch, because this is a BC break.
```markdown
- PHP 7.1 type hints
```
> Add type hints

- UPGRADE-4.0.md
- src/Admin/CkeditorAdminExtension.php
- src/Block/FormatterBlockService.php
- src/Controller/CkeditorAdminController.php
- src/DependencyInjection/Configuration.php
- src/DependencyInjection/SonataFormatterExtension.php
- src/Extension/ControlFlowExtension.php
- src/Extension/GistExtension.php
- src/Form/EventListener/FormatterListener.php
- src/Form/Type/FormatterType.php
- src/Form/Type/SimpleFormatterType.php
- src/Formatter/MarkdownFormatter.php
- src/Formatter/Pool.php
- src/Formatter/RawFormatter.php
- src/Formatter/TextFormatter.php
- src/Formatter/TwigFormatter.php
- src/SonataFormatterBundle.php
- src/Twig/Extension/TextFormatterExtension.php
- src/Twig/Loader/LoaderSelector.php
- src/Twig/Node/GistNode.php
- src/Twig/SecurityPolicyContainerAware.php
- src/Twig/TokenParser/GistTokenParser.php
- src/Validator/Constraints/Formatter.php
- src/Validator/Constraints/FormatterValidator.php
- tests/Form/Type/FormatterTypeTest.php
- tests/Validator/Constraints/FormatterValidatorTest.php
I am targeting this branch, because this is a BC break.
> Make Classes Final

- tests/Controller/CkeditorAdminControllerTest.php
- tests/Form/EventListener/FormatterListenerTest.php
- tests/Form/Type/FormatterTypeTest.php
- tests/Form/Type/SimpleFormatterTypeTest.php
- tests/Formatter/MarkdownFormatterTest.php
- tests/Formatter/PoolTest.php
- tests/Twig/Loader/LoaderSelectorTest.php
- tests/Validator/Constraints/FormatterValidatorTest.php
Backports style changes from #334
> Improve style

- docs/index.rst
- docs/reference/ckeditor_medias.rst
- docs/reference/formatter_block.rst
- docs/reference/formatter_widget.rst
- docs/reference/installation.rst
- docs/reference/usage.rst
To be review commit by commit.
> Improve docs

- src/Extension/BaseProxyExtension.php
I am targeting this branch, because it only appears in `master`.
Closes #348 (rework)
```markdown
- use the correct namespace for `ExtensionInterface`
```
> use correct interface. closes #348

- src/DependencyInjection/SonataFormatterExtension.php
- tests/DependencyInjection/SonataFormatterExtensionTest.php
I am targeting this branch, because this is pedantic.
This removes an unexpressed and unnecessary dependency to ext-json, and increases code coverage :)
> Remove dependency to ext-json

- composer.json
I am targeting this branch, because this is a patch.
```markdown
- Added missing `symfony/validator` dependency
```
> Added missing symfony/validator dependency

- .github/workflows/qa.yml
- phpstan.neon.dist
Improve code quality by running phpstan 🚀 
I am targeting this branch, because this is will help to improve code quality for the stable branch.
> Add phpstan checks

- src/Twig/SecurityPolicyContainerAware.php
```markdown
- potential crash in `SecurityPolicyContainerAware::checkMethodAllowed()`
```
> Fix sa findings

- composer.json
- phpstan.neon.dist
- src/DependencyInjection/SonataFormatterExtension.php
- src/Form/Type/FormatterType.php
- src/Form/Type/SimpleFormatterType.php
- src/Resources/config/form_fcke1.xml
- tests/Form/Type/LegacyFormatterTypeTest.php
- tests/Form/Type/LegacySimpleFormatterTypeTest.php
I am targeting this branch, because we try here to allow FOSCKEditor 2 in a BC way.
(Rework of https://github.com/sonata-project/SonataFormatterBundle/pull/467)
Allow FOSCKEditor dependency to ^2.0
```markdown
- Allow FOSCKEditor dependency to ^2.0
- Deprecate usage of FOSCKEditor ^1.0
```
> Allow FOSCKEditor dependency to 2.0 & start upgrade

- src/Resources/translations/SonataFormatterBundle.nl.xliff
Updates dutch translations
I am targeting this branch, because it only updates some translations
```markdown
- Updates dutch translations
```
> update dutch translations

- composer.json
- src/Block/FormatterBlockService.php
- src/Resources/config/block.xml
- tests/Block/FormatterBlockServiceTest.php
```markdown
- Add support for `sonata-project/block-bundle` 4.x
```
> Add support for sonata-project/block-bundle 4.x

- src/Resources/config/block.xml
I am targeting this branch, because {reason}.
Fixes #506
```markdown
- Fix `sonata.formatter.block.formatter` service registration
```
> Fix block di
